# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: BUSL-1.1

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: vault-kms-plugin-openshift-provider
    app.kubernetes.io/managed-by: kustomize
  name: controller-manager
  namespace: system
