apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: vault-kms-plugin-openshift-provider.v0.0.1
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions: {}
  description: Operator to define KMS plugin configuration for OpenShift clusters.
  displayName: Vault KMS Plugin OpenShift Provider
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: []
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  maturity: alpha
  provider:
    name: vault-kms-plugin-openshift-provider
  version: 0.0.1
