//go:build !ignore_autogenerated

// Copyright (c) HashiCorp, Inc.
// SPDX-License-Identifier: BUSL-1.1

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAppRoleAuthentication) DeepCopyInto(out *VaultAppRoleAuthentication) {
	*out = *in
	out.Secret = in.Secret
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAppRoleAuthentication.
func (in *VaultAppRoleAuthentication) DeepCopy() *VaultAppRoleAuthentication {
	if in == nil {
		return nil
	}
	out := new(VaultAppRoleAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultAuthentication) DeepCopyInto(out *VaultAuthentication) {
	*out = *in
	out.AppRole = in.AppRole
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultAuthentication.
func (in *VaultAuthentication) DeepCopy() *VaultAuthentication {
	if in == nil {
		return nil
	}
	out := new(VaultAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultConfigMapReference) DeepCopyInto(out *VaultConfigMapReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultConfigMapReference.
func (in *VaultConfigMapReference) DeepCopy() *VaultConfigMapReference {
	if in == nil {
		return nil
	}
	out := new(VaultConfigMapReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKMSConfig) DeepCopyInto(out *VaultKMSConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKMSConfig.
func (in *VaultKMSConfig) DeepCopy() *VaultKMSConfig {
	if in == nil {
		return nil
	}
	out := new(VaultKMSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultKMSConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKMSConfigList) DeepCopyInto(out *VaultKMSConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]VaultKMSConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKMSConfigList.
func (in *VaultKMSConfigList) DeepCopy() *VaultKMSConfigList {
	if in == nil {
		return nil
	}
	out := new(VaultKMSConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *VaultKMSConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKMSConfigSpec) DeepCopyInto(out *VaultKMSConfigSpec) {
	*out = *in
	out.TLS = in.TLS
	out.Authentication = in.Authentication
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKMSConfigSpec.
func (in *VaultKMSConfigSpec) DeepCopy() *VaultKMSConfigSpec {
	if in == nil {
		return nil
	}
	out := new(VaultKMSConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultKMSConfigStatus) DeepCopyInto(out *VaultKMSConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultKMSConfigStatus.
func (in *VaultKMSConfigStatus) DeepCopy() *VaultKMSConfigStatus {
	if in == nil {
		return nil
	}
	out := new(VaultKMSConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultSecretReference) DeepCopyInto(out *VaultSecretReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultSecretReference.
func (in *VaultSecretReference) DeepCopy() *VaultSecretReference {
	if in == nil {
		return nil
	}
	out := new(VaultSecretReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *VaultTLSConfig) DeepCopyInto(out *VaultTLSConfig) {
	*out = *in
	out.CABundle = in.CABundle
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new VaultTLSConfig.
func (in *VaultTLSConfig) DeepCopy() *VaultTLSConfig {
	if in == nil {
		return nil
	}
	out := new(VaultTLSConfig)
	in.DeepCopyInto(out)
	return out
}
